import { defineArrayMember, defineField, defineType } from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site settings',
  type: 'document',
  groups: [
    { name: 'brand', title: 'Brand', default: true },
    { name: 'nav', title: 'Navigation' },
    { name: 'footer', title: 'Footer' },
    { name: 'forms', title: 'Form messages' },
    { name: 'notFound', title: 'Page not found' },
  ],
  fields: [
    defineField({
      name: 'brandPrimary',
      title: 'Brand word (gold)',
      type: 'string',
      group: 'brand',
    }),
    defineField({
      name: 'brandSecondary',
      title: 'Brand word (tracked)',
      type: 'string',
      group: 'brand',
    }),
    defineField({ name: 'logo', type: 'figure', group: 'brand' }),
    defineField({ name: 'tagline', type: 'string', group: 'brand' }),
    defineField({
      name: 'conciergeEmail',
      title: 'Concierge email',
      type: 'string',
      group: 'brand',
    }),
    defineField({
      name: 'phone',
      type: 'string',
      group: 'brand',
    }),
    defineField({
      name: 'mailingAddress',
      title: 'Mailing address',
      description: 'One line per row.',
      type: 'text',
      rows: 3,
      group: 'brand',
    }),
    defineField({
      name: 'contactNote',
      title: 'Contact note',
      type: 'string',
      group: 'brand',
    }),
    defineField({
      name: 'primaryNav',
      title: 'Header navigation',
      type: 'array',
      of: [defineArrayMember({ type: 'link' })],
      group: 'nav',
    }),
    defineField({
      name: 'headerCta',
      title: 'Header button',
      type: 'link',
      group: 'nav',
    }),
    defineField({
      name: 'footerSiteLinks',
      title: 'Footer — Site column',
      type: 'array',
      of: [defineArrayMember({ type: 'link' })],
      group: 'footer',
    }),
    defineField({
      name: 'footerPortalLinks',
      title: 'Footer — Portals column',
      type: 'array',
      of: [defineArrayMember({ type: 'link' })],
      group: 'footer',
    }),
    defineField({
      name: 'secureNote',
      title: 'Footer — Secure note',
      type: 'text',
      rows: 3,
      group: 'footer',
    }),
    defineField({
      name: 'copyright',
      type: 'string',
      group: 'footer',
    }),
    defineField({
      name: 'footerHeadings',
      title: 'Footer — Column headings',
      type: 'object',
      options: { columns: 2 },
      group: 'footer',
      fields: [
        defineField({ name: 'site', type: 'string' }),
        defineField({ name: 'portals', type: 'string' }),
        defineField({ name: 'contact', type: 'string' }),
        defineField({ name: 'secure', type: 'string' }),
      ],
    }),
    defineField({
      name: 'formMessages',
      title: 'Form error messages',
      description: 'Shown on the title company and contact forms.',
      type: 'object',
      group: 'forms',
      fields: [
        defineField({ name: 'required', title: 'Missing required fields', type: 'string' }),
        defineField({ name: 'invalidEmail', title: 'Invalid email', type: 'string' }),
        defineField({ name: 'captcha', title: 'CAPTCHA not completed', type: 'string' }),
        defineField({ name: 'failed', title: 'Sending failed', type: 'text', rows: 2 }),
      ],
    }),
    defineField({
      name: 'notFound',
      title: 'Page not found (404)',
      type: 'object',
      group: 'notFound',
      fields: [
        defineField({ name: 'kicker', type: 'string' }),
        defineField({ name: 'heading', type: 'splitHeading' }),
        defineField({ name: 'body', type: 'text', rows: 2 }),
        defineField({ name: 'link', type: 'link' }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: 'Site settings' }) },
})
